### ISSUE TITLE
Maybe a BUG reporting : the returned idx in pointnet backbone implementation

### ISSUE THREAD

**Issue by slothfulxtx** [Ghostish/Open3DSOT#28]
Wonderful work! However,  I'm curious at this code in [models](https://github.com/Ghostish/Open3DSOT/tree/77f5d7919c6e05ab7df04623fc8a072da80d8b3a/models)/[backbone](https://github.com/Ghostish/Open3DSOT/tree/77f5d7919c6e05ab7df04623fc8a072da80d8b3a/models/backbone)/pointnet.py

```python
        for i in range(len(self.SA_modules)):
            li_xyz, li_features, sample_idxs = self.SA_modules[i](l_xyz[i], l_features[i], numpoints[i], True)
            l_xyz.append(li_xyz)
            l_features.append(li_features)
            l_idxs.append(sample_idxs)
        if self.return_intermediate:
            return l_xyz[1:], l_features[1:], l_idxs[0]
        return l_xyz[-1], l_features[-1], l_idxs[0]
```

It seems that the `idx` is used to generate corresponding segmentation ground truth mask for the downsampled search point clouds. Is it correct that  simply return `l_idxs[0]` instead of merge all the results in `l_idxs` ?

**Comment by Ghostish** [comment]
Yes, it is correct.
In our implementation, we have two strategies to sample a point cloud: either FPS or simply taking the first N points (equivalent to the random sampling when point clouds are orderless).
```python
        if self.use_fps:
            sample_idxs = pointnet2_utils.furthest_point_sample(xyz, self.npoint)
        else:
            sample_idxs = torch.arange(self.npoint).repeat(xyz.size(0), 1).int().cuda()
```
Besides,  when FPS is used, we only need to do FPS in the first layer due to the "farthest" nature.
Because of these, the remaining components of `l_ids`, which are always from 0~N, are useless. 
Only `l_idxs[0]` contains useful information when FPS is applied.
