### ISSUE TITLE
Hi author, can you provide a direct copy of the Nuscene SOT dataset that has been processed?

### ISSUE THREAD

**Issue by suyzhi** [Ghostish/Open3DSOT#44]
Hi author, can you provide a direct copy of the Nuscene SOT dataset that has been processed(.dat file)? At the same time, I would like to ask you what configuration is required to run the Nuscene dataset, and how long will the experiment take to train from scratch. I would appreciate it if you could answer my question.

**Comment by Ghostish** [comment]
Apologies for the inconvenience caused. Due to limitations in cloud space, we are unable to provide the large .dat files. However, you can easily run the NuScenes experiments using the provided config files. Using Multiple GPUs (e.g. 8 3080TIs) and with `--preloading` flag on (make sure you have enough CPU memory) is recommended to do the training.   The training time for a NuScenes model will depend on various factors, including your machine specifications, the chosen model types, and whether the --preloading flag is enabled, etc.

**Comment by suyzhi** [comment]
I am very grateful for your reply. This is a very valuable advice.
